# Generated by Django 4.2.1 on 2023-07-28 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('dt_id', models.AutoField(primary_key=True, serialize=False)),
                ('dt_name', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(max_length=100, null=True)),
                ('phone_dt', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('usertype', models.CharField(blank=True, max_length=100)),
                ('image_dt', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_date', models.DateField(auto_now_add=True, null=True)),
                ('total_money', models.DecimalField(decimal_places=3, max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('date_ob', models.DateField(blank=True, null=True)),
                ('phone_pt', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('usertype', models.CharField(blank=True, max_length=100)),
                ('image_pt', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='specialty',
            fields=[
                ('specialty_id', models.AutoField(primary_key=True, serialize=False)),
                ('specialty_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(blank=True, max_length=255, null=True)),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('usertype', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='medicalrecord',
            fields=[
                ('medicalrecord_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_med_exam', models.DateField(blank=True, null=True)),
                ('symptom', models.TextField(blank=True, null=True)),
                ('diagnostic', models.TextField(blank=True, null=True)),
                ('dt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models_API.doctor')),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models_API.invoice')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models_API.patient')),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(blank=True, max_length=100)),
                ('dateofjoining', models.DateField(blank=True, null=True)),
                ('photofilename', models.CharField(blank=True, max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models_API.department')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models_API.specialty'),
        ),
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('apm_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_med_exam', models.DateField(blank=True, null=True)),
                ('clinic', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=250)),
                ('note', models.TextField(blank=True)),
                ('dt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models_API.doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models_API.patient')),
            ],
        ),
    ]
