# Generated by Django 4.2.3 on 2023-08-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models_API', '0002_alter_patient_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_user',
            fields=[
                ('AdminId', models.AutoField(primary_key=True, serialize=False)),
                ('AdminName', models.CharField(blank=True, max_length=255, null=True)),
                ('FullName', models.CharField(blank=True, max_length=255, null=True)),
                ('Password', models.CharField(blank=True, max_length=255, null=True)),
                ('UserType', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='user_admin',
        ),
    ]
