# Generated by Django 4.2.3 on 2023-08-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models_API', '0003_admin_user_delete_user_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_user',
            old_name='AdminId',
            new_name='adminid',
        ),
        migrations.RemoveField(
            model_name='admin_user',
            name='AdminName',
        ),
        migrations.RemoveField(
            model_name='admin_user',
            name='FullName',
        ),
        migrations.RemoveField(
            model_name='admin_user',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='admin_user',
            name='UserType',
        ),
        migrations.AddField(
            model_name='admin_user',
            name='adminname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='admin_user',
            name='fullname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admin_user',
            name='password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='admin_user',
            name='usertype',
            field=models.CharField(blank=True, default='Admin', max_length=10),
        ),
    ]
